#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/jewerly-db-sem
#    password: 1k7Gj5Pp
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jewerly-db-sem
    username: postgres
    password: password
  database:
    driverClassName: org.postgresql.Driver
  thymeleaf:
    cache: false
